
services:
    ems.ldap_user_provider:
        class: EMS\CoreBundle\Security\CoreLdapUserProvider
        arguments:
            $doctrine: '@doctrine'
            $extraFieldsService: '@EMS\CoreBundle\Security\LdapExtraFields'
            $userService: '@ems.service.user'
            $ldap: '@Symfony\Component\Ldap\Ldap'
            $baseDn: '%ems_core.ldap.base_dn%'
            $searchDn: '%ems_core.ldap.search_dn%'
            $searchPassword: '%ems_core.ldap.search_password%'
            $defaultRoles: '%ems_core.ldap.default_roles%'
            $uidKey: '%ems_core.ldap.uid_key%'
            $filter: '%ems_core.ldap.filter%'
            $passwordAttribute: '%ems_core.ldap.password_attribute%'
            $extraFields: '%ems_core.ldap.extra_fields%'
    EMS\CoreBundle\Security\LdapExtraFields:
        arguments:
            $email: '%ems_core.ldap.email_field%'
            $displayName: '%ems_core.ldap.display_name_field%'
            $givenName: '%ems_core.ldap.given_name_field%'
            $lastName: '%ems_core.ldap.last_name_field%'
