<?php

namespace EMS\CoreBundle\Repository;

/**
 * FieldTypeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FieldTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
