<?php

namespace EMS\CoreBundle\Repository;

/**
 * LinkRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkRepository extends \Doctrine\ORM\EntityRepository
{
}
