<?php

namespace EMS\CoreBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
interface UserRepositoryInterface
{
    /**
     *
     * @param string $role
     * @param array<string> $circles
     * @return array <\EMS\CoreBundle\Entity\User>
     */
    public function findForRoleAndCircles($role, $circles);
    
    /**
     *
     * @return \EMS\CoreBundle\Core\User\UserList
     */
    public function getUsersEnabled();
}
