<?php

namespace Ems\CoreBundle\Repository;


/**
 * AuditRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuditRepository extends \Doctrine\ORM\EntityRepository
{
}
