<?php

declare(strict_types=1);

namespace EMS\CoreBundle\Repository;

/**
 * AuthTokenRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthTokenRepository extends \Doctrine\ORM\EntityRepository
{
}
