<?php

namespace EMS\CoreBundle\Repository;

use EMS\CoreBundle\Entity\ContentType;

/**
 * ContentTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentTypeRepository extends \Doctrine\ORM\EntityRepository
{
	
	public function findAllAsAssociativeArray(){
		$qb = $this->createQueryBuilder('ct');
		$qb->where($qb->expr()->eq('ct.deleted', 0));
		
		$out = [];
		$result = $qb->getQuery()->getResult();
		/** @var \EMS\CoreBundle\Entity\ContentType $record */
		foreach ($result as $record){
			$out[$record->getName()] = $record;
		}
		
		return $out;
	}


	/**
	 * 
	 * @param string $name
	 * @return ContentType
	 */
	public function findByName($name) {
		return $this->findOneBy([
				'deleted' => false,
				'name' => $name,
		]);
	}
	
	public function countContentType() {
		return $this->createQueryBuilder('a')
		 ->select('COUNT(a)')
		 ->getQuery()
		 ->getSingleScalarResult();
	}
	
	
	public function maxOrderKey() {
		return $this->createQueryBuilder('a')
		 ->select('max(a.orderKey)')
		 ->getQuery()
		 ->getSingleScalarResult();
	}
}
