<?php

namespace EMS\CoreBundle\Repository;


/**
 * AuditRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilterRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByName($name){
        return $this->findOneBy([
                'name' => $name,
        ]);
    }
}
