<?php

namespace EMS\CoreBundle\Repository;

/**
 * UploadedAssetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UploadedAssetRepository extends \Doctrine\ORM\EntityRepository
{
}
