<?php declare(strict_types=1);

namespace Application\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20200226102551 extends AbstractMigration
{
    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'sqlite', 'Migration can only be executed safely on \'sqlite\'.');

        $this->addSql('DROP INDEX tuple_index');
        $this->addSql('CREATE TEMPORARY TABLE __temp__revision AS SELECT id, content_type_id, created, modified, auto_save_at, deleted, version, start_time, end_time, draft, lock_by, auto_save_by, lock_until, labelField, finalized_by, sha1, deleted_by, finalized_date, raw_data, auto_save, circles, ouuid FROM revision');
        $this->addSql('DROP TABLE revision');
        $this->addSql('CREATE TABLE revision (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, content_type_id BIGINT DEFAULT NULL, created DATETIME NOT NULL, modified DATETIME NOT NULL, auto_save_at DATETIME DEFAULT NULL, deleted BOOLEAN NOT NULL, version INTEGER DEFAULT 1 NOT NULL, start_time DATETIME NOT NULL, end_time DATETIME DEFAULT NULL, draft BOOLEAN NOT NULL, lock_by VARCHAR(255) DEFAULT NULL COLLATE BINARY, auto_save_by VARCHAR(255) DEFAULT NULL COLLATE BINARY, lock_until DATETIME DEFAULT NULL, labelField CLOB DEFAULT NULL COLLATE BINARY, finalized_by VARCHAR(255) DEFAULT NULL COLLATE BINARY, sha1 VARCHAR(255) DEFAULT NULL COLLATE BINARY, deleted_by VARCHAR(255) DEFAULT NULL COLLATE BINARY, finalized_date DATETIME DEFAULT NULL, raw_data CLOB DEFAULT NULL COLLATE BINARY --(DC2Type:json_array)
        , auto_save CLOB DEFAULT NULL COLLATE BINARY --(DC2Type:json_array)
        , circles CLOB DEFAULT NULL COLLATE BINARY --(DC2Type:simple_array)
        , ouuid VARCHAR(255) DEFAULT NULL COLLATE BINARY)');
        $this->addSql('INSERT INTO revision (id, content_type_id, created, modified, auto_save_at, deleted, version, start_time, end_time, draft, lock_by, auto_save_by, lock_until, labelField, finalized_by, sha1, deleted_by, finalized_date, raw_data, auto_save, circles, ouuid) SELECT id, content_type_id, created, modified, auto_save_at, deleted, version, start_time, end_time, draft, lock_by, auto_save_by, lock_until, labelField, finalized_by, sha1, deleted_by, finalized_date, raw_data, auto_save, circles, ouuid FROM __temp__revision');
        $this->addSql('DROP TABLE __temp__revision');
        $this->addSql('CREATE UNIQUE INDEX tuple_index ON revision (end_time, ouuid)');
        $this->addSql('DROP INDEX UNIQ_41BCBAEC588AB49A');
        $this->addSql('CREATE TEMPORARY TABLE __temp__content_type AS SELECT id, field_types_id, environment_id, created, modified, name, pluralName, singularName, icon, description, indexTwig, extra, lockBy, lockUntil, circles_field, deleted, have_pipelines, ask_for_ouuid, dirty, color, labelField, color_field, parentField, userField, dateField, startDateField, endDateField, locationField, referer_field_name, category_field, ouuidField, imageField, videoField, email_field, asset_field, order_field, sort_by, create_role, edit_role, view_role, orderKey, rootContentType, edit_twig_with_wysiwyg, active, publish_role, trash_role, sort_order, web_content, default_value, auto_publish, business_id_field, translationField, localeField FROM content_type');
        $this->addSql('DROP TABLE content_type');
        $this->addSql('CREATE TABLE content_type (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, field_types_id INTEGER DEFAULT NULL, environment_id INTEGER DEFAULT NULL, created DATETIME NOT NULL, modified DATETIME NOT NULL, name VARCHAR(100) NOT NULL COLLATE BINARY, pluralName VARCHAR(100) NOT NULL COLLATE BINARY, singularName VARCHAR(100) NOT NULL COLLATE BINARY, icon VARCHAR(100) DEFAULT NULL COLLATE BINARY, description CLOB DEFAULT NULL COLLATE BINARY, indexTwig CLOB DEFAULT NULL COLLATE BINARY, extra CLOB DEFAULT NULL COLLATE BINARY, lockBy VARCHAR(100) DEFAULT NULL COLLATE BINARY, lockUntil DATETIME DEFAULT NULL, circles_field VARCHAR(100) DEFAULT NULL COLLATE BINARY, deleted BOOLEAN NOT NULL, have_pipelines BOOLEAN DEFAULT NULL, ask_for_ouuid BOOLEAN NOT NULL, dirty BOOLEAN NOT NULL, color VARCHAR(50) DEFAULT NULL COLLATE BINARY, labelField VARCHAR(100) DEFAULT NULL COLLATE BINARY, color_field VARCHAR(100) DEFAULT NULL COLLATE BINARY, parentField VARCHAR(100) DEFAULT NULL COLLATE BINARY, userField VARCHAR(100) DEFAULT NULL COLLATE BINARY, dateField VARCHAR(100) DEFAULT NULL COLLATE BINARY, startDateField VARCHAR(100) DEFAULT NULL COLLATE BINARY, endDateField VARCHAR(100) DEFAULT NULL COLLATE BINARY, locationField VARCHAR(100) DEFAULT NULL COLLATE BINARY, referer_field_name VARCHAR(100) DEFAULT NULL COLLATE BINARY, category_field VARCHAR(100) DEFAULT NULL COLLATE BINARY, ouuidField VARCHAR(100) DEFAULT NULL COLLATE BINARY, imageField VARCHAR(100) DEFAULT NULL COLLATE BINARY, videoField VARCHAR(100) DEFAULT NULL COLLATE BINARY, email_field VARCHAR(100) DEFAULT NULL COLLATE BINARY, asset_field VARCHAR(100) DEFAULT NULL COLLATE BINARY, order_field VARCHAR(100) DEFAULT NULL COLLATE BINARY, sort_by VARCHAR(100) DEFAULT NULL COLLATE BINARY, create_role VARCHAR(100) DEFAULT NULL COLLATE BINARY, edit_role VARCHAR(100) DEFAULT NULL COLLATE BINARY, view_role VARCHAR(100) DEFAULT NULL COLLATE BINARY, orderKey INTEGER NOT NULL, rootContentType BOOLEAN NOT NULL, edit_twig_with_wysiwyg BOOLEAN NOT NULL, active BOOLEAN NOT NULL, publish_role VARCHAR(100) DEFAULT NULL COLLATE BINARY, trash_role VARCHAR(100) DEFAULT NULL COLLATE BINARY, sort_order VARCHAR(4) DEFAULT \'asc\' COLLATE BINARY, web_content BOOLEAN DEFAULT \'1\' NOT NULL, default_value CLOB DEFAULT NULL COLLATE BINARY, auto_publish BOOLEAN DEFAULT \'0\' NOT NULL, business_id_field VARCHAR(100) DEFAULT NULL COLLATE BINARY, translationField VARCHAR(100) DEFAULT NULL COLLATE BINARY, localeField VARCHAR(100) DEFAULT NULL COLLATE BINARY, searchLinkDisplayRole VARCHAR(255) DEFAULT \'ROLE_USER\' NOT NULL, createLinkDisplayRole VARCHAR(255) DEFAULT \'ROLE_USER\' NOT NULL)');
        $this->addSql('INSERT INTO content_type (id, field_types_id, environment_id, created, modified, name, pluralName, singularName, icon, description, indexTwig, extra, lockBy, lockUntil, circles_field, deleted, have_pipelines, ask_for_ouuid, dirty, color, labelField, color_field, parentField, userField, dateField, startDateField, endDateField, locationField, referer_field_name, category_field, ouuidField, imageField, videoField, email_field, asset_field, order_field, sort_by, create_role, edit_role, view_role, orderKey, rootContentType, edit_twig_with_wysiwyg, active, publish_role, trash_role, sort_order, web_content, default_value, auto_publish, business_id_field, translationField, localeField) SELECT id, field_types_id, environment_id, created, modified, name, pluralName, singularName, icon, description, indexTwig, extra, lockBy, lockUntil, circles_field, deleted, have_pipelines, ask_for_ouuid, dirty, color, labelField, color_field, parentField, userField, dateField, startDateField, endDateField, locationField, referer_field_name, category_field, ouuidField, imageField, videoField, email_field, asset_field, order_field, sort_by, create_role, edit_role, view_role, orderKey, rootContentType, edit_twig_with_wysiwyg, active, publish_role, trash_role, sort_order, web_content, default_value, auto_publish, business_id_field, translationField, localeField FROM __temp__content_type');
        $this->addSql('DROP TABLE __temp__content_type');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_41BCBAEC588AB49A ON content_type (field_types_id)');
        $this->addSql('ALTER TABLE environment ADD COLUMN snapshot BOOLEAN DEFAULT \'0\' NOT NULL');
        $this->addSql('CREATE TEMPORARY TABLE __temp__single_type_index AS SELECT id, content_type_id, environment_id, created, modified, name FROM single_type_index');
        $this->addSql('DROP TABLE single_type_index');
        $this->addSql('CREATE TABLE single_type_index (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, content_type_id BIGINT DEFAULT NULL, environment_id INTEGER DEFAULT NULL, created DATETIME NOT NULL, modified DATETIME NOT NULL, name VARCHAR(255) NOT NULL COLLATE BINARY)');
        $this->addSql('INSERT INTO single_type_index (id, content_type_id, environment_id, created, modified, name) SELECT id, content_type_id, environment_id, created, modified, name FROM __temp__single_type_index');
        $this->addSql('DROP TABLE __temp__single_type_index');
        $this->addSql('DROP INDEX UNIQ_B4F0DBA71A445520');
        $this->addSql('CREATE TEMPORARY TABLE __temp__search AS SELECT id, content_type_id, username, contentTypes, name, sort_by, sort_order, default_search, environments, minimum_should_match FROM search');
        $this->addSql('DROP TABLE search');
        $this->addSql('CREATE TABLE search (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, content_type_id BIGINT DEFAULT NULL, username VARCHAR(100) NOT NULL COLLATE BINARY, contentTypes CLOB NOT NULL COLLATE BINARY --(DC2Type:json_array)
        , name VARCHAR(100) NOT NULL COLLATE BINARY, sort_by VARCHAR(100) DEFAULT NULL COLLATE BINARY, sort_order VARCHAR(100) DEFAULT NULL COLLATE BINARY, default_search BOOLEAN DEFAULT \'0\' NOT NULL, environments CLOB NOT NULL COLLATE BINARY --(DC2Type:json_array)
        , minimum_should_match INTEGER DEFAULT 1 NOT NULL)');
        $this->addSql('INSERT INTO search (id, content_type_id, username, contentTypes, name, sort_by, sort_order, default_search, environments, minimum_should_match) SELECT id, content_type_id, username, contentTypes, name, sort_by, sort_order, default_search, environments, minimum_should_match FROM __temp__search');
        $this->addSql('DROP TABLE __temp__search');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B4F0DBA71A445520 ON search (content_type_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__search_filter AS SELECT id, search_id, pattern, field, boolean_clause, operator, boost FROM search_filter');
        $this->addSql('DROP TABLE search_filter');
        $this->addSql('CREATE TABLE search_filter (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, search_id BIGINT DEFAULT NULL, pattern VARCHAR(200) DEFAULT NULL COLLATE BINARY, field VARCHAR(100) DEFAULT NULL COLLATE BINARY, boolean_clause VARCHAR(20) DEFAULT NULL COLLATE BINARY, operator VARCHAR(50) NOT NULL COLLATE BINARY, boost NUMERIC(10, 2) DEFAULT NULL)');
        $this->addSql('INSERT INTO search_filter (id, search_id, pattern, field, boolean_clause, operator, boost) SELECT id, search_id, pattern, field, boolean_clause, operator, boost FROM __temp__search_filter');
        $this->addSql('DROP TABLE __temp__search_filter');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'sqlite', 'Migration can only be executed safely on \'sqlite\'.');

        $this->addSql('DROP TABLE session');
        $this->addSql('DROP INDEX UNIQ_41BCBAEC588AB49A');
        $this->addSql('CREATE TEMPORARY TABLE __temp__content_type AS SELECT id, created, modified, name, pluralName, singularName, icon, description, indexTwig, extra, lockBy, lockUntil, circles_field, business_id_field, deleted, have_pipelines, ask_for_ouuid, dirty, color, labelField, color_field, parentField, userField, dateField, startDateField, endDateField, locationField, referer_field_name, category_field, ouuidField, imageField, videoField, email_field, asset_field, order_field, sort_by, sort_order, create_role, edit_role, view_role, publish_role, trash_role, orderKey, rootContentType, edit_twig_with_wysiwyg, web_content, auto_publish, active, default_value, translationField, localeField, field_types_id, environment_id FROM content_type');
        $this->addSql('DROP TABLE content_type');
        $this->addSql('CREATE TABLE content_type (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, created DATETIME NOT NULL, modified DATETIME NOT NULL, name VARCHAR(100) NOT NULL, pluralName VARCHAR(100) NOT NULL, singularName VARCHAR(100) NOT NULL, icon VARCHAR(100) DEFAULT NULL, description CLOB DEFAULT NULL, indexTwig CLOB DEFAULT NULL, extra CLOB DEFAULT NULL, lockBy VARCHAR(100) DEFAULT NULL, lockUntil DATETIME DEFAULT NULL, circles_field VARCHAR(100) DEFAULT NULL, business_id_field VARCHAR(100) DEFAULT NULL, deleted BOOLEAN NOT NULL, have_pipelines BOOLEAN DEFAULT NULL, ask_for_ouuid BOOLEAN NOT NULL, dirty BOOLEAN NOT NULL, color VARCHAR(50) DEFAULT NULL, labelField VARCHAR(100) DEFAULT NULL, color_field VARCHAR(100) DEFAULT NULL, parentField VARCHAR(100) DEFAULT NULL, userField VARCHAR(100) DEFAULT NULL, dateField VARCHAR(100) DEFAULT NULL, startDateField VARCHAR(100) DEFAULT NULL, endDateField VARCHAR(100) DEFAULT NULL, locationField VARCHAR(100) DEFAULT NULL, referer_field_name VARCHAR(100) DEFAULT NULL, category_field VARCHAR(100) DEFAULT NULL, ouuidField VARCHAR(100) DEFAULT NULL, imageField VARCHAR(100) DEFAULT NULL, videoField VARCHAR(100) DEFAULT NULL, email_field VARCHAR(100) DEFAULT NULL, asset_field VARCHAR(100) DEFAULT NULL, order_field VARCHAR(100) DEFAULT NULL, sort_by VARCHAR(100) DEFAULT NULL, sort_order VARCHAR(4) DEFAULT \'asc\', create_role VARCHAR(100) DEFAULT NULL, edit_role VARCHAR(100) DEFAULT NULL, view_role VARCHAR(100) DEFAULT NULL, publish_role VARCHAR(100) DEFAULT NULL, trash_role VARCHAR(100) DEFAULT NULL, orderKey INTEGER NOT NULL, rootContentType BOOLEAN NOT NULL, edit_twig_with_wysiwyg BOOLEAN NOT NULL, web_content BOOLEAN DEFAULT \'1\' NOT NULL, auto_publish BOOLEAN DEFAULT \'0\' NOT NULL, active BOOLEAN NOT NULL, default_value CLOB DEFAULT NULL, translationField VARCHAR(100) DEFAULT NULL, localeField VARCHAR(100) DEFAULT NULL, field_types_id INTEGER DEFAULT NULL, environment_id INTEGER DEFAULT NULL)');
        $this->addSql('INSERT INTO content_type (id, created, modified, name, pluralName, singularName, icon, description, indexTwig, extra, lockBy, lockUntil, circles_field, business_id_field, deleted, have_pipelines, ask_for_ouuid, dirty, color, labelField, color_field, parentField, userField, dateField, startDateField, endDateField, locationField, referer_field_name, category_field, ouuidField, imageField, videoField, email_field, asset_field, order_field, sort_by, sort_order, create_role, edit_role, view_role, publish_role, trash_role, orderKey, rootContentType, edit_twig_with_wysiwyg, web_content, auto_publish, active, default_value, translationField, localeField, field_types_id, environment_id) SELECT id, created, modified, name, pluralName, singularName, icon, description, indexTwig, extra, lockBy, lockUntil, circles_field, business_id_field, deleted, have_pipelines, ask_for_ouuid, dirty, color, labelField, color_field, parentField, userField, dateField, startDateField, endDateField, locationField, referer_field_name, category_field, ouuidField, imageField, videoField, email_field, asset_field, order_field, sort_by, sort_order, create_role, edit_role, view_role, publish_role, trash_role, orderKey, rootContentType, edit_twig_with_wysiwyg, web_content, auto_publish, active, default_value, translationField, localeField, field_types_id, environment_id FROM __temp__content_type');
        $this->addSql('DROP TABLE __temp__content_type');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_41BCBAEC588AB49A ON content_type (field_types_id)');
        $this->addSql('DROP INDEX UNIQ_4626DE225E237E06');
        $this->addSql('CREATE TEMPORARY TABLE __temp__environment AS SELECT id, created, modified, name, alias, color, baseUrl, managed, circles, in_default_search, extra, order_key FROM environment');
        $this->addSql('DROP TABLE environment');
        $this->addSql('CREATE TABLE environment (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, created DATETIME NOT NULL, modified DATETIME NOT NULL, name VARCHAR(255) NOT NULL, alias VARCHAR(255) NOT NULL, color VARCHAR(50) DEFAULT NULL, baseUrl VARCHAR(1024) DEFAULT NULL, managed BOOLEAN NOT NULL, circles CLOB DEFAULT NULL --(DC2Type:json_array)
        , in_default_search BOOLEAN DEFAULT NULL, extra CLOB DEFAULT NULL, order_key INTEGER DEFAULT NULL)');
        $this->addSql('INSERT INTO environment (id, created, modified, name, alias, color, baseUrl, managed, circles, in_default_search, extra, order_key) SELECT id, created, modified, name, alias, color, baseUrl, managed, circles, in_default_search, extra, order_key FROM __temp__environment');
        $this->addSql('DROP TABLE __temp__environment');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4626DE225E237E06 ON environment (name)');
        $this->addSql('DROP INDEX tuple_index');
        $this->addSql('CREATE TEMPORARY TABLE __temp__revision AS SELECT id, created, modified, auto_save_at, deleted, version, ouuid, start_time, end_time, draft, finalized_by, finalized_date, deleted_by, lock_by, auto_save_by, lock_until, raw_data, auto_save, circles, labelField, sha1, content_type_id FROM revision');
        $this->addSql('DROP TABLE revision');
        $this->addSql('CREATE TABLE revision (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, created DATETIME NOT NULL, modified DATETIME NOT NULL, auto_save_at DATETIME DEFAULT NULL, deleted BOOLEAN NOT NULL, version INTEGER DEFAULT 1 NOT NULL, start_time DATETIME NOT NULL, end_time DATETIME DEFAULT NULL, draft BOOLEAN NOT NULL, finalized_by VARCHAR(255) DEFAULT NULL, finalized_date DATETIME DEFAULT NULL, deleted_by VARCHAR(255) DEFAULT NULL, lock_by VARCHAR(255) DEFAULT NULL, auto_save_by VARCHAR(255) DEFAULT NULL, lock_until DATETIME DEFAULT NULL, raw_data CLOB DEFAULT NULL --(DC2Type:json_array)
        , auto_save CLOB DEFAULT NULL --(DC2Type:json_array)
        , circles CLOB DEFAULT NULL --(DC2Type:simple_array)
        , labelField CLOB DEFAULT NULL, sha1 VARCHAR(255) DEFAULT NULL, content_type_id BIGINT DEFAULT NULL, ouuid VARCHAR(255) DEFAULT NULL COLLATE BINARY)');
        $this->addSql('INSERT INTO revision (id, created, modified, auto_save_at, deleted, version, ouuid, start_time, end_time, draft, finalized_by, finalized_date, deleted_by, lock_by, auto_save_by, lock_until, raw_data, auto_save, circles, labelField, sha1, content_type_id) SELECT id, created, modified, auto_save_at, deleted, version, ouuid, start_time, end_time, draft, finalized_by, finalized_date, deleted_by, lock_by, auto_save_by, lock_until, raw_data, auto_save, circles, labelField, sha1, content_type_id FROM __temp__revision');
        $this->addSql('DROP TABLE __temp__revision');
        $this->addSql('CREATE UNIQUE INDEX tuple_index ON revision (end_time, ouuid)');
    }
}
