name: Close Pull Request

on:
    pull_request_target:
        types: [opened]

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - uses: superbrothers/close-pull-request@v3
              with:
                  comment: "Read only repository, make pr on https://github.com/ems-project/elasticms."